name: Install HiFiBGC on macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: macos-12
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true
        python-version: 3.9
        
    - name: Create and activate conda environment
      run: |
        conda create -n hifibgc -c conda-forge -c bioconda -c amityadav -y hifibgc
        conda init
        conda activate hifibgc
        
    - name: Test HiFiBGC installation
      run: |
        hifibgc --help
