name: Install HiFiBGC on macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    #strategy:
    #  matrix:
    #    os: [macos-12, ubuntu-20.04]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        python-version: 3.9

    - name: Install hifibgc using pip and test it
      shell: bash -l {0}
      run: |
        conda create -n hifibgc_14a2_conda -c conda-forge -c bioconda -c amityadav hifibgc==0.1.14a2 -y
        conda activate hifibgc_14a2_conda
        hifibgc -h
        hifibgc install -p
        hifibgc test -p
        
        #conda create -n hifibgc_14a2_pip -c conda-forge python=3.11 -y 
        #conda activate hifibgc_14a2_pip
        #pip install hifibgc==0.1.14a2
        #hifibgc -h
        #hifibgc install -p --conda-frontend conda
        #hifibgc test -p --conda-frontend conda
  
        #wget https://raw.githubusercontent.com/ay-amityadav/github_actions_test/main/base1_macos_installation.yml
        #conda env create --name base1 --file=base1_macos_installation.yml
        #conda activate base1
        #git clone -b macos_installation https://github.com/ay-amityadav/HiFiBGC.git
        #cd HiFiBGC/hifibgc
        #python __main__.py install -p --conda-frontend conda
        #python __main__.py test -p --conda-frontend conda  
        
        
        
        
        
    

        
