name: Install HiFiBGC on macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: macos-12
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        python-version: 3.9
        mamba-version: "*"

    - name: Install hifibgc using mamba and test it
      shell: bash -l {0}
      run: |
        mamba create -n hifibgc_14_conda -c conda-forge -c bioconda -c amityadav hifibgc -y
        conda activate hifibgc_14_conda
        hifibgc -h
        hifibgc install -p
        hifibgc test -p
