name: Install HiFiBGC on macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: macos-12
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        python-version: 3.9

    - name: Create and activate conda environment
      shell: bash -l {0}
      run: |
        wget https://raw.githubusercontent.com/ay-amityadav/github_actions_test/main/hifiasm_meta_minimal_mac.yml
        conda env create --name hifiasm_meta_minimal_mac --file=hifiasm_meta_minimal_mac.yml
        conda activate hifiasm_meta_minimal_mac
        hifiasm_meta -h
        gfatools version
        
        
        
        
    

        
