name: Install HiFiBGC on macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          #activate-environment: anaconda-client-env
      - shell: bash -el {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort
      - shell: bash -el {0}
        run: |
          mamba create -n hifibgc -c conda-forge -c bioconda -c amityadav -y hifibgc
      - name: Initialize Mamba
        shell: bash -l {0}
        run: |
          conda activate hifibgc
          hifibgc -h
          hifibgc install -p
          hifibgc test -p
    # steps:
    # - name: Checkout repository
    #   uses: actions/checkout@v3
      
    # - name: Set up Mambaforge
    #   uses: conda-incubator/setup-miniconda@v2
    #   with:
    #     miniforge-variant: Mambaforge
    #     miniforge-version: latest
    #     activate-environment: myenv
    #     use-mamba: true

    # - name: Initialize Mamba
    #   shell: bash -l {0}
    #   run: |
    #     mamba init bash
    #     source ~/.bash_profile

    # - name: Install your tool
    #   shell: bash -l {0}
    #   run: |
    #     mamba create -n hifibgc -c conda-forge -c bioconda -c amityadav -y hifibgc
    #     # mamba init
    #     # mamba activate hifibgc
    #     # hifibgc -h

    # - name: Verify installation
    #   shell: bash -l {0}
    #   run: |
    #    mamba activate hifibgc
    #    hifibgc -h
    #    hifibgc install -p
    #    hifibgc test -p
       
    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.9'

    # - name: Install Miniconda
    #   uses: conda-incubator/setup-miniconda@v2
    #   with:
    #     auto-activate-base: false
    #     python-version: 3.9

    # - name: Install hifibgc using pip and test it
    #   shell: bash -l {0}
    #   run: |
    #     conda create -n hifibgc_14_pip -c conda-forge python=3.11 -y 
    #     conda activate hifibgc_14_pip
    #     pip install hifibgc
    #     hifibgc -h
    #     hifibgc install -p --conda-frontend conda
    #     hifibgc test -p --conda-frontend conda

    # - name: Install hifibgc using conda and test it
    #   shell: bash -l {0}
    #   run: |
    #     conda create -n hifibgc_14_conda -c conda-forge -c bioconda -c amityadav hifibgc -y
    #     conda activate hifibgc_14_conda
    #     hifibgc -h
    #     hifibgc install -p
    #     hifibgc test -p
